from staze.core.error.error import Error


class LogError(Error): pass
